### ISSUE TITLE
Documento de ejemplo de figma

### ISSUE THREAD

**Issue by goiblas** [Alvaro07/figma-tokens-app#10]
Hola,
Tiene muy buena pinta la herramienta, pero no soy capaz de hacerla funcionar, siempre recibo "invalid data".
¿Qué debería ser el token name, un frame, un componentes, un estilo?
Creo que puedo ayudar tener un documento de figma de ejemplo, si no tienes ninguno que se pueda compartir, no me importar crear un sencillito pero necesito saber cómo debe ser.
Gracias

**Comment by Alvaro07** [comment]
Hola @goiblas 

La herramienta aún esta en desarrollo, y en cuanto pueda la documentaré.

Mientras la puedes probar manteniendo una estructura definida en figma, en esta primera prueba todos los tokens son del tipo `RECTANGLE`, ya que los de tipo `FRAME` los reconoce como grupo, que mediante una función recursiva navega sobre los mismos para generar los diferentes tokens finales asociados a ese grupo.

Te dejo un ejemplo dónde `color-light` es el nombre del token, *text* es el nombre del grupo y *buttonDisabled* es el nombre/valor del token final (el grupo no es necesario).

![token-screenshot](https://user-images.githubusercontent.com/17145093/83513204-b92bd880-a4d1-11ea-986e-54e9a1cbb241.PNG)

Igualmente la gestión de errores está pendiente, ya que si el nombre no es el correcto, o la estructura falla el error será el mismo, `invalid data`

**Comment by goiblas** [comment]
Gracias @Alvaro07 
Funciona de maravilla, la herramienta siempre está en desarrollo ;)
